name: build
on:
  push:
    branches:
      - master
    paths:
      - 'build.gradle'
      - 'gradle.properties'
      - 'src/**'
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout code from repo
      uses: actions/checkout@v1

    - name: Install Java 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build plugin
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: buildPlugin
        gradle-version: 6.5

    - name: Run Linters and Test
      run: ./gradlew check

    - name: Verify Plugin
      run: ./gradlew verifyPlugin

    - name: Run Plugin Verifier
      run: ./gradlew runPluginVerifier -Pplugin.verifier.home.dir=~/.pluginVerifier
