name: coverage
on:
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: macos-latest
    steps:
    - name: Checkout code from "master"
      uses: actions/checkout@v1
    - name: Setup Java environment
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run tests
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test jacocoTestReport --warning-mode none
        gradle-version: 6.5
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true
