name: IntelliJ Platform Plugin Compatibility

on:
  push:

jobs:
  compatibility:
    name: Ensure plugin compatibility against IDEA, PyCharm  and the latest IEAD EAP
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          ide-versions: |
            ideaIC:2020.1.4
            ideaIU:2020.1.4
            pycharmPC:2020.1.4
            pycharmPY:2020.1.4
            ideaIC:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}